[package]
name = "payx"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
rust_decimal = { version = "1.40", features = ["macros"] }
serde = { version = "1", features = ["derive"] }
indexmap = "2.13"
thiserror = "2.0"
anyhow = "1.0.102"
